import type { Metadata } from "next";
import { Open_Sans, Playwrite_NG_Modern } from "next/font/google";
import "./globals.css";
import Dashboard from "@/components/dashboard/dashboard-layout";

const openSans = Open_Sans({
  variable: "--font-open-sans",
});

const playWriteNg = Playwrite_NG_Modern({
  variable: "--font-playwrite-ng",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} ${playWriteNg.variable} antialiased`}
      >
        <Dashboard>
        {children}
        </Dashboard>
      </body>
    </html>
  );
}
